version: '3'

services:
  sidekick-web-ui:
    image: embernet/sidekick-web-ui:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: always
    depends_on:
      - sidekick-server

  sidekick-server:
    image: embernet/sidekick-server:latest
    ports:
      - "127.0.0.1:8000:5000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
