version: '3'

services:
  sidekick-web-ui:
    image: sidekick-web-ui:latest
    ports:
      - "8081:8081"
    environment:
      - REACT_APP_SERVER_URL=http://127.0.0.1:8000
    restart: always
    depends_on:
      - sidekick-server

  sidekick-server:
    image: sidekick-server:latest
    ports:
      - "127.0.0.1:8000:80"
    env_file:
      - .env
    restart: always
