version: '3'

services:
  sidekick-web-ui:
    image: localhost:5001/sidekick-web-ui:latest
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - REACT_APP_SERVER_URL=***
    restart: always

  sidekick-server:
    image: localhost:5001/sidekick-server:latest
    ports:
      - "5004:5004"
    volumes:
      - ./data:/data
      - ./etc:/etc
    environment:
      - OPENAI_API_KEY=***
      - JWT_SECRET=***
    restart: always

