"""Add visibility column to documents model

Revision ID: 1815a78b3b41
Revises: f8ac702d8453
Create Date: 2024-01-23 15:34:58.324167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1815a78b3b41'
down_revision = 'f8ac702d8453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE documents SET visibility='private' WHERE visibility IS NULL")

    # Alter columns to set nullable=False with default values
    with op.batch_alter_table('documents', schema=None) as batch_op:
        # Set nullable=False for 'name' column with a default value
        batch_op.alter_column('visibility', existing_type=sa.String(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
