"""Add size column to documents model

Revision ID: 4e52a8b4c8f1
Revises: 1815a78b3b41
Create Date: 2024-08-21 23:53:42.827639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e52a8b4c8f1'
down_revision = '1815a78b3b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE documents SET size = LENGTH(content)")

    # Alter column to set nullable=False 
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('size', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
