"""Add user name and is_oidc columns

Revision ID: f8ac702d8453
Revises: 73f445469feb
Create Date: 2023-11-17 15:07:46.984280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ac702d8453'
down_revision = '73f445469feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add columns with nullable=True
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_oidc', sa.Boolean(), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE users SET name='', is_oidc=False WHERE name IS NULL "
               "OR is_oidc IS NULL")

    # Alter columns to set nullable=False with default values
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Set nullable=False for 'name' column with a default value
        batch_op.alter_column('name', existing_type=sa.String(),
                              nullable=False)

        # Set nullable=False for 'is_oidc' column with a default value
        batch_op.alter_column('is_oidc', existing_type=sa.Boolean(),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_oidc')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
